// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/okey-variants/MinimalTactical.tsx": () => import("../components/mockups/okey-variants/MinimalTactical.tsx"),
  "./components/mockups/okey-variants/MobileDrawer.tsx": () => import("../components/mockups/okey-variants/MobileDrawer.tsx"),
  "./components/mockups/okey-variants/PhysicalTable.tsx": () => import("../components/mockups/okey-variants/PhysicalTable.tsx"),
  "./components/mockups/okey-variants/StreamerDash.tsx": () => import("../components/mockups/okey-variants/StreamerDash.tsx")
};
